import { useMemo, useState } from 'react'
import { ArrowUpRight } from 'lucide-react'
import { products, whatsapp } from '../data/products'

const categories = ['All', ...new Set(products.map((product) => product.category))]
const productImages = import.meta.glob('../assets/products-new/*', { eager: true, import: 'default' })

export default function Products() {
  const [activeCategory, setActiveCategory] = useState('All')
  const visibleProducts = useMemo(() => activeCategory === 'All' ? products : products.filter((product) => product.category === activeCategory), [activeCategory])
  return <section id="products" className="section-shell"><div className="max-w-2xl"><p className="eyebrow">Shop the collection</p><h2 className="section-title">Made to carry<br/><i>your everyday.</i></h2><p className="body-copy">Quilted, block-printed accessories created in Jaipur. Tap a collection to browse, then message us directly to order.</p></div><div className="mt-9 flex flex-wrap gap-2" aria-label="Filter products by collection">{categories.map((category) => <button type="button" key={category} onClick={() => setActiveCategory(category)} className={`filter-chip ${activeCategory === category ? 'filter-chip-active' : ''}`} aria-pressed={activeCategory === category}>{category}</button>)}</div><div className="mt-10 grid gap-x-5 gap-y-10 sm:grid-cols-2 lg:grid-cols-3">{visibleProducts.map((product, index) => {const message = encodeURIComponent(`Hello Craft of Pink City, I would like to order the ${product.name} (${product.price}). Is it available?`);return <article className="product-card group" key={product.name}><div className="product-photo-wrap"><img className="product-photo" src={productImages[`../assets/products-new/${product.image}`]} alt={product.name} loading={index < 3 ? 'eager' : 'lazy'} decoding="async"/><span className="product-category">{product.category}</span></div><div className="mt-4 flex items-start justify-between gap-3"><div><h3 className="font-serif text-3xl leading-none text-ink">{product.name}</h3><p className="mt-2 text-sm leading-5 text-ink/65">{product.description}</p></div><span className="shrink-0 font-serif text-xl text-rose">{product.price}</span></div><a className="product-enquiry" href={`${whatsapp}?text=${message}`} target="_blank" rel="noreferrer" aria-label={`Enquire about ${product.name} on WhatsApp`}>Enquire on WhatsApp <ArrowUpRight size={16}/></a></article>})}</div></section>
}
